### ISSUE TITLE
The retry logic in the VersionResolver fails if one of the repositories is unavailable

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/wildfly-channel#243]
When resolving artifact from two or more repositries, if one of those is returning error code different then 404 (e.g. 503), the request will fail even though the other repository contains this artifact.

Example

```
            final Channel channel = new Channel.Builder()
                    .addRepository("public-ga", "http://localhost:8888/")    // always returns 503
                    .addRepository("mrrc", "https://maven.repository.redhat.com/ga/")
                    .setManifestCoordinate(new ChannelManifestCoordinate("org.jboss.eap.channels", "eap-8.0"))
                    .build();
            final ChannelSession channelSession = new ChannelSession(List.of(channel), new VersionResolverFactory(system, session));
```
Exception:
```
org.wildfly.channel.ArtifactTransferException: org.jboss.eap.channels:eap-8.0/maven-metadata.xml failed to transfer from http://localhost:8888/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of public-ga has elapsed or updates are forced. Original error: Could not transfer metadata org.jboss.eap.channels:eap-8.0/maven-metadata.xml from/to public-ga (http://localhost:8888/): status code: 503, reason phrase: Service Unavailable (503)

	at org.wildfly.channel.maven.RetryHandler$RetryCounter.addRetry(RetryHandler.java:151)
	at org.wildfly.channel.maven.RetryHandler.attemptResolveMetadata(RetryHandler.java:116)
	at org.wildfly.channel.maven.VersionResolverFactory$MavenResolverImpl.getAllVersions(VersionResolverFactory.java:152)
	at org.wildfly.channel.maven.VersionResolverFactory$MavenResolverImpl.resolveChannelMetadata(VersionResolverFactory.java:263)
	at org.wildfly.channel.ChannelImpl.resolveManifest(ChannelImpl.java:200)
	at org.wildfly.channel.ChannelImpl.init(ChannelImpl.java:85)
	at org.wildfly.channel.ChannelSession.<init>(ChannelSession.java:90)
	at org.wildfly.channel.ChannelSession.<init>(ChannelSession.java:64)
	at org.wildfly.prospero.api.TestResolver.downloadAndUnzipRemoteArchive(TestResolver.java:87)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.eclipse.aether.transfer.MetadataTransferException: org.jboss.eap.channels:eap-8.0/maven-metadata.xml failed to transfer from http://localhost:8888/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of public-ga has elapsed or updates are forced. Original error: Could not transfer metadata org.jboss.eap.channels:eap-8.0/maven-metadata.xml from/to public-ga (http://localhost:8888/): status code: 503, reason phrase: Service Unavailable (503)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:331)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkMetadata(DefaultUpdateCheckManager.java:293)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:303)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:180)
	at org.apache.maven.repository.internal.DefaultVersionRangeResolver.getVersions(DefaultVersionRangeResolver.java:198)
	at org.apache.maven.repository.internal.DefaultVersionRangeResolver.resolveVersionRange(DefaultVersionRangeResolver.java:148)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveVersionRange(DefaultRepositorySystem.java:260)
	at org.wildfly.channel.maven.VersionResolverFactory$MavenResolverImpl.lambda$getAllVersions$0(VersionResolverFactory.java:154)
	at org.wildfly.channel.maven.RetryHandler.attemptResolveMetadata(RetryHandler.java:96)
	... 33 more
```

**Comment by spyrkob** [comment]
Thinking about this I'm not sure what is the correct behaviour. In this scenario, if one of the repositories is returning errors, we don't know if that repository have any artifacts versions to contribute. If we return partial results we might be getting wrong version of artifact or, even worse the manifest,  without any means to really inform the user apart from a log message that can be disabled. 

So in this case it feels like throwing exception if there are any transfer errors is the right thing to do... @ivassile, @jmesnil WDYT?

**Comment by ivassile** [comment]
I think we have to keep the current behaviour and throw an exception if there are transfer errors. This helped us identify the MRRC caching issue and it's better than masking the problem and not discovering potential issues. If you expect to find only specific artifacts in a repo, the channel configuration should have the streams listed (Example [1]: "eap8-amq-channel" and "eap8-insights-channel")

[1] https://gitlab.cee.redhat.com/jboss-set/channel-definitions/-/raw/main/eap-8.0.x/latest/channel.yaml

**Comment by spyrkob** [comment]
I'm going to close this, as I think the behaviour is correct
